# Generated by Django 5.1.1 on 2024-10-23 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок вашего блога', max_length=25, verbose_name='Заголовок блога')),
                ('text', models.TextField(help_text='Добавьте ваш текст', verbose_name='Текст блога')),
                ('image', models.ImageField(help_text='Добавьте изображение', upload_to='blog/photo', verbose_name='Изображение')),
                ('created_at', models.DateField(default=django.utils.timezone.now, help_text='Введите дату добавления продукта', verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='Флаг публикации')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['created_at'],
            },
        ),
    ]
