# Generated by Django 5.1.1 on 2024-10-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Введите описание продукта', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='catalog/photo', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Введите цену продукта', max_length=50, verbose_name='Цена')),
                ('created_at', models.DateField(blank=True, help_text='Введите дату добавления продукта', null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, help_text='Введите дату изменения продукта', null=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['name', 'price'],
            },
        ),
    ]
